-- V11__user_password_change_and_role_grants.sql — KH-2.2b-BE (spec FS-2.2 D5/D6/D8). Schema only.
-- Flyway is the ONLY source of schema (ddl-auto: validate). Do not edit this file after it has
-- been applied anywhere — append a new one instead.
--
-- Two genuinely-new schema needs this session's user-management surface introduces:
--
-- (1) must_change_password flag on app_user. A user provisioned with a temporary password (D5
--     create / reset-password, D6 initialAdmin) is created with this set; every authenticated
--     call except the self-service POST /api/v1/users/me/password is rejected with 403 KH-USR-0403
--     while it is set (rbac.security.PasswordChangeEnforcementFilter), and it is cleared the
--     moment the user sets a real password. DEFAULT false so every existing user — including
--     AdminBootstrap's env-var-passworded admin, who authenticates with a real password — is
--     unaffected and never forced through the change step.
--
-- (2) GRANT DELETE on user_role to khatm_app. Replacing a user's role set (POST /{id}/roles,
--     D5) is DELETE-all-then-INSERT on the join table. V7__rls_policies.sql granted DELETE to
--     khatm_app on exactly one table, consuming_party_schema, for the identical reason
--     (disallowSchema's idempotent removal); this extends the same documented exception to
--     user_role. No DELETE grant on app_user or role themselves — deletion is still not a
--     supported business path (FS-0.2 D6) — only on this join table, for role-set replacement.

ALTER TABLE app_user ADD COLUMN must_change_password boolean NOT NULL DEFAULT false;

GRANT DELETE ON user_role TO khatm_app;
