-- V16__tenant_hierarchy.sql — KH-2.6a-BE (spec FS-2.5 §1/§2/§7): the tenant hierarchy's data
-- foundation. Administrative-only per FS-2.5 §1 ("الهرمية إدارية، لا أمنية ولا تشفيرية") —
-- parent_tenant_id is pure organisational metadata. Key separation is untouched (every tenant,
-- parent or child, still signs with its own key, publishes its own JWKS, owns its own status
-- list). Flyway is the ONLY source of schema. Do not edit this file after it has been applied
-- anywhere — append a new migration instead.
--
-- Additive-only: every existing row's new parent_tenant_id is NULL (a root), so no live data is
-- touched. `tenant` itself is excluded from Row-Level Security (V7's own comment: "the admin
-- plane reads/writes it directly; it has no tenant_id of its own to filter by") — this migration
-- does not add, remove, or alter any RLS policy anywhere (FS-2.5 §1's absolute red line).

ALTER TABLE tenant ADD COLUMN parent_tenant_id uuid REFERENCES tenant(id);

-- Self-parent guard, the cheap half of hierarchy integrity a CHECK constraint can express
-- directly. Cycles and the max-depth guard (spec §7: three levels) need to walk the ancestor
-- chain, which a CHECK constraint cannot do — see the trigger below for those two.
ALTER TABLE tenant
  ADD CONSTRAINT tenant_parent_not_self CHECK (parent_tenant_id IS NULL OR parent_tenant_id <> id);

CREATE INDEX tenant_parent_tenant_id ON tenant (parent_tenant_id);

-- Depth/cycle guard (spec §7, decided 2026-08-18: max depth THREE levels, adjacency-list model
-- unchanged — raising the limit later is a guard change here, never a data migration). This is
-- defense-in-depth: sy.khatm.platform.tenant.domain.TenantAdminService#setParent already performs
-- the identical walk in Java and rejects with a friendly KH-TNT-042x error code before ever
-- reaching this statement in the normal path — this trigger exists so the invariant holds even
-- against a write that bypasses the service layer (a direct SQL statement, a future call site that
-- forgets the check), the same "service check first, DB constraint as the real backstop" posture
-- V7's tenant_isolation policy already established for RLS. Bounded recursion (`lvl < 10`) is a
-- pure safety margin — three levels never gets close to it — in case corrupt pre-existing data
-- ever produced a real cycle upstream of this trigger.
CREATE OR REPLACE FUNCTION enforce_tenant_hierarchy_depth() RETURNS trigger AS $$
DECLARE
  ancestor_count int;
  would_cycle boolean;
BEGIN
  IF NEW.parent_tenant_id IS NULL THEN
    RETURN NEW;
  END IF;

  WITH RECURSIVE ancestors AS (
    SELECT t.id, t.parent_tenant_id, 1 AS lvl
    FROM tenant t
    WHERE t.id = NEW.parent_tenant_id
    UNION ALL
    SELECT t.id, t.parent_tenant_id, a.lvl + 1
    FROM tenant t
    JOIN ancestors a ON t.id = a.parent_tenant_id
    WHERE a.lvl < 10
  )
  SELECT count(*), bool_or(id = NEW.id) INTO ancestor_count, would_cycle FROM ancestors;

  IF would_cycle THEN
    RAISE EXCEPTION 'tenant hierarchy cycle: % is already an ancestor of %', NEW.id, NEW.parent_tenant_id
      USING ERRCODE = '23514';
  END IF;

  IF ancestor_count >= 3 THEN
    RAISE EXCEPTION 'tenant hierarchy depth exceeded: parent % is already at the maximum depth (3)', NEW.parent_tenant_id
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tenant_hierarchy_depth_guard
  BEFORE INSERT OR UPDATE OF parent_tenant_id ON tenant
  FOR EACH ROW EXECUTE FUNCTION enforce_tenant_hierarchy_depth();
