-- V18__issuer_client.sql — KH-2.8.1-BE (spec FS-2.7a D1/D9): machine-to-machine issuer clients.
-- Additive-only. Flyway is the ONLY source of schema. Do not edit this file after it has been
-- applied anywhere — append a new migration instead.
--
-- issuer_client mirrors consuming_party's shape (bilingual name, per-tenant, N-N schema allowlist)
-- but carries its own credential: key_prefix (ten base32 characters, stored WITHOUT the "khi_" tag so
-- a dump scan for "khi_" can never match a stored prefix) and api_key_hash (argon2id of the secret
-- only, UTF-8 bytes of the encoded string). The raw key is shown once at creation/rotation and is
-- never persisted anywhere.

CREATE TABLE issuer_client (
  id           uuid PRIMARY KEY,
  tenant_id    uuid NOT NULL REFERENCES tenant(id),
  name_i18n    jsonb NOT NULL,
  key_prefix   text NOT NULL UNIQUE,
  api_key_hash bytea NOT NULL,
  scopes       text[] NOT NULL,
  status       text NOT NULL DEFAULT 'ACTIVE'
                 CHECK (status IN ('ACTIVE', 'SUSPENDED', 'RETIRING', 'REVOKED')),
  rotated_from uuid REFERENCES issuer_client(id),
  retire_after timestamptz,
  expires_at   timestamptz,
  last_used_at timestamptz,
  created_by   uuid,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT issuer_client_name_i18n_langs CHECK (name_i18n ? 'en' AND name_i18n ? 'ar'),
  -- v1: the single permitted scope is 'issue'. Widened later by a new migration (never by editing this one).
  CONSTRAINT issuer_client_scopes_allowed
    CHECK (cardinality(scopes) >= 1 AND scopes <@ ARRAY['issue']::text[]),
  CONSTRAINT issuer_client_retire_after_needs_retiring
    CHECK (retire_after IS NULL OR status IN ('RETIRING', 'REVOKED'))
);

CREATE INDEX issuer_client_tenant_status ON issuer_client (tenant_id, status);
CREATE INDEX issuer_client_retiring ON issuer_client (retire_after) WHERE status = 'RETIRING';

CREATE TABLE issuer_client_schema (
  issuer_client_id uuid NOT NULL REFERENCES issuer_client(id),
  schema_id        uuid NOT NULL REFERENCES credential_schema(id),
  tenant_id        uuid NOT NULL REFERENCES tenant(id),
  PRIMARY KEY (issuer_client_id, schema_id)
);

CREATE INDEX issuer_client_schema_tenant ON issuer_client_schema (tenant_id);

-- Which client issued a credential (NULL for console-session issuance).
ALTER TABLE credential ADD COLUMN issuer_client_id uuid REFERENCES issuer_client(id);
CREATE INDEX credential_issuer_client ON credential (issuer_client_id) WHERE issuer_client_id IS NOT NULL;

-- Same strict-equality RLS shape as V7 (tenant_isolation + system_access), no exceptions.
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['issuer_client', 'issuer_client_schema']
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON %I USING'
        || ' (tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid)',
      t);
    EXECUTE format(
      'CREATE POLICY system_access ON %I USING (current_setting(''app.khatm_system'', true) = ''on'')',
      t);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE ON %I TO khatm_app', t);
  END LOOP;
END $$;
