-- V19__issuance_idempotency.sql — KH-2.8.2-BE (spec FS-2.7a D5–D7): persistent issuance idempotency.
-- Additive-only. Flyway is the ONLY source of schema. Do not edit this file after it has been
-- applied anywhere — append a new migration instead.
--
-- One row per (tenant, issuer client | human session, scope, Idempotency-Key). The unique index is
-- what resolves a concurrent retry race (in the database, not in code — the ConcurrentConsumeTest
-- lesson). Proofs only (P1): the row holds a hash of the request body, never the body, and the
-- BULK result snapshot holds indices/ids/refs/error codes, never a claim code or a claim value.

CREATE TABLE issuance_idempotency (
  id               uuid PRIMARY KEY,
  tenant_id        uuid NOT NULL REFERENCES tenant(id),
  -- NULL = a human (console) session; such callers share one per-tenant key namespace.
  issuer_client_id uuid NULL REFERENCES issuer_client(id),
  idempotency_key  text NOT NULL CHECK (length(idempotency_key) BETWEEN 1 AND 128),
  scope            text NOT NULL CHECK (scope IN ('ISSUE', 'BULK')),
  -- SHA-256 of the canonical JSON request body (keys sorted, nulls dropped).
  request_hash     bytea NOT NULL CHECK (length(request_hash) = 32),
  state            text NOT NULL CHECK (state IN ('IN_PROGRESS', 'DONE')),
  credential_id    uuid NULL REFERENCES credential(id),      -- ISSUE
  result_snapshot  jsonb NULL,                               -- BULK: per-row results, no codes
  created_at       timestamptz NOT NULL DEFAULT now(),
  expires_at       timestamptz NOT NULL
);

CREATE UNIQUE INDEX issuance_idem_key
  ON issuance_idempotency (
    tenant_id,
    COALESCE(issuer_client_id, '00000000-0000-0000-0000-000000000000'::uuid),
    scope,
    idempotency_key);

-- The worker-role retention sweeper deletes by expiry.
CREATE INDEX issuance_idem_expires ON issuance_idempotency (expires_at);

-- Same strict-equality RLS shape as V7/V18 (tenant_isolation + system_access), no exceptions.
ALTER TABLE issuance_idempotency ENABLE ROW LEVEL SECURITY;
ALTER TABLE issuance_idempotency FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON issuance_idempotency USING
  (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);
CREATE POLICY system_access ON issuance_idempotency USING
  (current_setting('app.khatm_system', true) = 'on');
-- DELETE is granted for the retention sweeper (runs under system access only).
GRANT SELECT, INSERT, UPDATE, DELETE ON issuance_idempotency TO khatm_app;
