-- V1__baseline.sql — KH-0.2.1 enterprise database baseline.
-- Source of truth: specs/FS-0.2-database-baseline.md. Flyway is the ONLY source of schema
-- (ddl-auto: validate). Do not edit this file after it has been applied anywhere — append a
-- new migration instead.
--
-- Cross-cutting decisions (spec §2), applied to every business table below:
--   D1  id uuid PK, generated application-side as UUIDv7 (no DB default).
--   D2  tenant_id uuid NOT NULL on every business table, composite indexes lead with it.
--   D3  All timestamps are timestamptz (UTC); formatting is a client concern.
--   D4  Human-facing names: name_i18n jsonb NOT NULL, {"en":"…","ar":"…"}, CHECK enforces both keys.
--   D5  Status columns: text + CHECK, never a Postgres enum (avoids locking ALTER TYPE later).
--   D6  No ON DELETE CASCADE on business tables — deletion is not a supported path (audit NFR-08).
--   D7  Counters are int/bigint, never float.
--   D8  created_at defaults to now(); updated_at (where present) is maintained by a shared trigger.
--   D9  P1 — no column stores unfolded claim values or PII (claim_code is the one, short-lived,
--       encrypted exception — see §3.7).

-- ── Shared trigger: maintain updated_at ─────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ── 3.1 tenant — the issuing organisation ───────────────────────────────────────────────────
CREATE TABLE tenant (
  id           uuid PRIMARY KEY,
  slug         text NOT NULL UNIQUE,
  name_i18n    jsonb NOT NULL,
  type         text NOT NULL CHECK (type IN ('GOVERNMENT','EDUCATION','PRIVATE','OTHER')),
  did          text UNIQUE,
  deploy_mode  text NOT NULL DEFAULT 'SAAS' CHECK (deploy_mode IN ('SAAS','ONPREM','FEDERATED')),
  status       text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','SUSPENDED')),
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tenant_name_i18n_langs CHECK (name_i18n ? 'en' AND name_i18n ? 'ar')
);

CREATE TRIGGER tenant_set_updated_at
  BEFORE UPDATE ON tenant
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ── 3.2 issuer_key — signing keys (rotation-ready from day one) ────────────────────────────
CREATE TABLE issuer_key (
  id           uuid PRIMARY KEY,
  tenant_id    uuid NOT NULL REFERENCES tenant(id),
  kid          text NOT NULL,
  algo         text NOT NULL DEFAULT 'ES256' CHECK (algo IN ('ES256')),
  public_jwk   jsonb NOT NULL,
  provider     text NOT NULL DEFAULT 'SOFT' CHECK (provider IN ('SOFT','KMS','PKCS11')),
  provider_ref text,
  state        text NOT NULL DEFAULT 'ACTIVE' CHECK (state IN ('PENDING','ACTIVE','RETIRING','RETIRED')),
  valid_from   timestamptz NOT NULL,
  valid_to     timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, kid)
);

CREATE UNIQUE INDEX issuer_key_one_active
  ON issuer_key (tenant_id) WHERE state = 'ACTIVE';

-- ── 3.3 credential_schema — document type registry ─────────────────────────────────────────
CREATE TABLE credential_schema (
  id               uuid PRIMARY KEY,
  tenant_id        uuid NOT NULL REFERENCES tenant(id),
  code             text NOT NULL,
  version          int  NOT NULL DEFAULT 1,
  name_i18n        jsonb NOT NULL,
  claims_def       jsonb NOT NULL,
  sd_fields        text[] NOT NULL DEFAULT '{}',
  default_max_uses int NOT NULL DEFAULT 1 CHECK (default_max_uses >= 1),
  default_validity interval,
  status           text NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','PUBLISHED','DEPRECATED')),
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, code, version),
  CONSTRAINT schema_name_i18n_langs CHECK (name_i18n ? 'en' AND name_i18n ? 'ar')
);

CREATE TRIGGER credential_schema_set_updated_at
  BEFORE UPDATE ON credential_schema
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ── 3.4 holder — pseudonymous holder ────────────────────────────────────────────────────────
CREATE TABLE holder (
  id          uuid PRIMARY KEY,
  tenant_id   uuid NOT NULL REFERENCES tenant(id),
  pseudo_ref  text NOT NULL,
  wallet_jwk  jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, pseudo_ref)
);

-- ── 3.5 status_list — compact revocation list (Status List 2021 style bitstring) ────────────
CREATE TABLE status_list (
  id                  uuid PRIMARY KEY,
  tenant_id           uuid NOT NULL REFERENCES tenant(id),
  list_code           text NOT NULL,
  bitstring           bytea NOT NULL,
  capacity            int  NOT NULL DEFAULT 131072,
  next_idx            int  NOT NULL DEFAULT 0,
  version             bigint NOT NULL DEFAULT 0,
  signed_artifact_ref text,
  published_at        timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, list_code)
);

-- ── 3.6 credential — the core aggregate ─────────────────────────────────────────────────────
CREATE TABLE credential (
  id             uuid PRIMARY KEY,
  tenant_id      uuid NOT NULL REFERENCES tenant(id),
  schema_id      uuid NOT NULL REFERENCES credential_schema(id),
  holder_id      uuid NOT NULL REFERENCES holder(id),
  ref            text NOT NULL UNIQUE,
  copy_of        uuid REFERENCES credential(id),
  signed_payload text NOT NULL,
  payload_hash   bytea NOT NULL,
  status_list_id uuid NOT NULL REFERENCES status_list(id),
  status_idx     int  NOT NULL,
  valid_from     timestamptz NOT NULL,
  valid_to       timestamptz NOT NULL,
  max_uses       int  NOT NULL CHECK (max_uses >= 1),
  uses_remaining int  NOT NULL CHECK (uses_remaining >= 0),
  revoked        boolean NOT NULL DEFAULT false,
  revoked_at     timestamptz,
  issued_by      uuid,
  created_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (status_list_id, status_idx),
  CHECK (valid_to > valid_from),
  CHECK (uses_remaining <= max_uses)
);

CREATE INDEX credential_tenant_schema ON credential (tenant_id, schema_id);
CREATE INDEX credential_holder        ON credential (tenant_id, holder_id);
CREATE INDEX credential_active_window ON credential (valid_to) WHERE revoked = false;

-- ── 3.7 claim_code — one-time wallet claim, the sole exception to P1 ───────────────────────
CREATE TABLE claim_code (
  id              uuid PRIMARY KEY,
  tenant_id       uuid NOT NULL REFERENCES tenant(id),
  credential_id   uuid NOT NULL REFERENCES credential(id),
  code_hash       bytea NOT NULL UNIQUE,
  disclosures_enc bytea,
  expires_at      timestamptz NOT NULL,
  claimed_at      timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- ── 3.8 consuming_party — verifier/relying-party registry ──────────────────────────────────
CREATE TABLE consuming_party (
  id           uuid PRIMARY KEY,
  tenant_id    uuid NOT NULL REFERENCES tenant(id),
  name_i18n    jsonb NOT NULL,
  api_key_hash bytea NOT NULL UNIQUE,
  status       text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','SUSPENDED')),
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT cp_name_i18n_langs CHECK (name_i18n ? 'en' AND name_i18n ? 'ar')
);

CREATE TABLE consuming_party_schema (
  consuming_party_id uuid NOT NULL REFERENCES consuming_party(id),
  schema_id          uuid NOT NULL REFERENCES credential_schema(id),
  PRIMARY KEY (consuming_party_id, schema_id)
);

-- ── 3.9 consumption_event — consumption ledger ──────────────────────────────────────────────
CREATE TABLE consumption_event (
  id                 uuid PRIMARY KEY,
  tenant_id          uuid NOT NULL REFERENCES tenant(id),
  credential_id      uuid NOT NULL REFERENCES credential(id),
  consuming_party_id uuid NOT NULL REFERENCES consuming_party(id),
  idempotency_key    text NOT NULL,
  mode               text NOT NULL CHECK (mode IN ('ONLINE','OFFLINE')),
  consumed_at        timestamptz NOT NULL DEFAULT now(),
  merkle_leaf        bytea,
  receipt_sig        bytea,
  UNIQUE (idempotency_key)
);

CREATE INDEX consumption_event_credential  ON consumption_event (credential_id);
CREATE INDEX consumption_event_party_time  ON consumption_event (tenant_id, consuming_party_id, consumed_at);

-- ── 3.10 RBAC — app_user / role / user_role ─────────────────────────────────────────────────
CREATE TABLE app_user (
  id                uuid PRIMARY KEY,
  tenant_id         uuid NOT NULL REFERENCES tenant(id),
  username          text NOT NULL,
  password_hash     text NOT NULL,
  display_name_i18n jsonb NOT NULL,
  preferred_lang    text NOT NULL DEFAULT 'ar' CHECK (preferred_lang IN ('en','ar')),
  status            text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','LOCKED','DISABLED')),
  created_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, username)
);

CREATE TABLE role (
  id        uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenant(id),
  code      text NOT NULL,
  name_i18n jsonb NOT NULL,
  scopes    text[] NOT NULL,
  UNIQUE (tenant_id, code)
);

CREATE TABLE user_role (
  user_id uuid NOT NULL REFERENCES app_user(id),
  role_id uuid NOT NULL REFERENCES role(id),
  PRIMARY KEY (user_id, role_id)
);

-- ── 3.11 audit_log — append-only audit trail (NFR-08) ───────────────────────────────────────
CREATE TABLE audit_log (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id   uuid NOT NULL,
  actor_type  text NOT NULL CHECK (actor_type IN ('USER','API_KEY','SYSTEM')),
  actor_id    uuid,
  action      text NOT NULL,
  entity_type text NOT NULL,
  entity_ref  text,
  detail      jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION audit_log_block_mutation() RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'audit_log is append-only'; END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_log_no_update BEFORE UPDATE OR DELETE ON audit_log
  FOR EACH ROW EXECUTE FUNCTION audit_log_block_mutation();

-- ── 3.12 event_publication — Spring Modulith JDBC event publication registry (ADR-09) ──────
-- Official schema, copied verbatim from spring-modulith-events-jdbc:1.2.4
-- (schema-postgresql.sql). No custom design here — this table is owned by the library.
CREATE TABLE IF NOT EXISTS event_publication
(
  id               UUID NOT NULL,
  listener_id      TEXT NOT NULL,
  event_type       TEXT NOT NULL,
  serialized_event TEXT NOT NULL,
  publication_date TIMESTAMP WITH TIME ZONE NOT NULL,
  completion_date  TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS event_publication_serialized_event_hash_idx ON event_publication USING hash(serialized_event);
CREATE INDEX IF NOT EXISTS event_publication_by_completion_date_idx ON event_publication (completion_date);

-- ── Seed: default tenant + 3 default roles (documented fixed UUIDs; MVP single-tenant) ─────
-- The default tenant id is mirrored in Java as sy.khatm.platform.shared.TenantContext.
INSERT INTO tenant (id, slug, name_i18n, type, deploy_mode, status)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  'khatm-default',
  '{"en":"Khatm Default Tenant","ar":"مستأجر ختم الافتراضي"}'::jsonb,
  'GOVERNMENT',
  'SAAS',
  'ACTIVE'
);

INSERT INTO role (id, tenant_id, code, name_i18n, scopes) VALUES
  ('00000000-0000-0000-0000-0000000000a1', '00000000-0000-0000-0000-000000000001',
   'PLATFORM_ADMIN', '{"en":"Platform Administrator","ar":"مدير المنصة"}'::jsonb,
   ARRAY['issue','verify','consume','revoke','admin']),
  ('00000000-0000-0000-0000-0000000000a2', '00000000-0000-0000-0000-000000000001',
   'TENANT_ADMIN', '{"en":"Tenant Administrator","ar":"مدير الجهة"}'::jsonb,
   ARRAY['issue','verify','consume','revoke','admin']),
  ('00000000-0000-0000-0000-0000000000a3', '00000000-0000-0000-0000-000000000001',
   'ISSUER_OPERATOR', '{"en":"Issuer Operator","ar":"مشغّل الإصدار"}'::jsonb,
   ARRAY['issue','verify']);
