-- V2__auth_api_keys.sql — KH-0.6b (spec FS-0.6b §4): API key registry, replacing the single
-- hash-only column consuming_party had since V1. Flyway is the ONLY source of schema
-- (ddl-auto: validate). Do not edit this file after it has been applied anywhere — append a
-- new migration instead.
--
-- D3: a general api_key table (owner_type TENANT | CONSUMING_PARTY) replaces
-- consuming_party.api_key_hash — the old column supported neither prefix-based lookup nor
-- overlapping-validity rotation (two keys valid at once during a rollover).

CREATE TABLE api_key (
  id           uuid PRIMARY KEY,
  tenant_id    uuid NOT NULL REFERENCES tenant(id),
  owner_type   text NOT NULL CHECK (owner_type IN ('TENANT','CONSUMING_PARTY')),
  owner_id     uuid,                              -- NULL when TENANT (the owner is tenant_id)
  key_prefix   text NOT NULL UNIQUE,               -- lookup — safe to log
  key_hash     bytea NOT NULL,                     -- SHA-256(secret) — D4
  scopes       text[] NOT NULL,                    -- subset of the scope catalog
  status       text NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','REVOKED')),
  created_at   timestamptz NOT NULL DEFAULT now(),
  revoked_at   timestamptz,
  last_used_at timestamptz                         -- best-effort update; never fails the request
);

CREATE INDEX api_key_owner ON api_key (tenant_id, owner_type, owner_id);

ALTER TABLE consuming_party DROP COLUMN api_key_hash;   -- D3
