-- V7__rls_policies.sql — KH-2.1-BE Part B (spec FS-2.1 D2/D3): Postgres Row-Level Security, the
-- real multi-tenant isolation boundary enforced by the database itself, not just service-layer
-- discipline. Flyway is the ONLY source of schema. Do not edit this file after it has been
-- applied anywhere — append a new migration instead.
--
-- Table list verified against the LIVE schema (V1-V6 applied), not against FS-0.2's original
-- design doc, per this session's own verify-against-the-code duty: two join tables
-- (consuming_party_schema, user_role) turned out to have NO tenant_id column at all (composite
-- PK only) — backfilled below so every RLS-protected table shares one identical policy shape,
-- rather than writing one-off join-through policies for just these two. `tenant` itself is
-- excluded (the admin plane reads/writes it directly; it has no tenant_id of its own to filter
-- by — spec D2).

-- ── Backfill tenant_id onto the two join tables that don't have one ────────────────────────
ALTER TABLE consuming_party_schema ADD COLUMN tenant_id uuid;
UPDATE consuming_party_schema cps
  SET tenant_id = cp.tenant_id
  FROM consuming_party cp
  WHERE cp.id = cps.consuming_party_id;
ALTER TABLE consuming_party_schema ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE consuming_party_schema
  ADD CONSTRAINT consuming_party_schema_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenant(id);
CREATE INDEX consuming_party_schema_tenant ON consuming_party_schema (tenant_id);

ALTER TABLE user_role ADD COLUMN tenant_id uuid;
UPDATE user_role ur
  SET tenant_id = au.tenant_id
  FROM app_user au
  WHERE au.id = ur.user_id;
ALTER TABLE user_role ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE user_role
  ADD CONSTRAINT user_role_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenant(id);
CREATE INDEX user_role_tenant ON user_role (tenant_id);

-- ── RLS on every business table carrying tenant_id (14 total; `tenant` excluded) ───────────
-- Two PERMISSIVE policies per table (spec D2/D5 — Postgres ORs multiple permissive policies):
--   tenant_isolation — the normal request path. app.tenant_id is set transaction-scoped (never
--     SET SESSION — forbidden, D4) from the resolved principal by a hook keyed on
--     shared.TenantContext.current(), which falls back to the default tenant when nothing set
--     it explicitly — so every pre-KH-2.1 code path (seeders, single-tenant tests, the
--     default tenant's own traffic) keeps working unchanged under RLS with zero call-site
--     changes. NULLIF(..., '') before the ::uuid cast matters empirically: a custom GUC that has
--     never been touched in this session resolves via current_setting(..., true)'s missing_ok to
--     a real NULL, but once ANY transaction on a pooled connection has SET LOCAL'd it even once,
--     Postgres remembers the parameter exists and reverts it to its bootValue — the empty string
--     — for every later transaction that never sets it again, not NULL. A bare ::uuid cast of ''
--     is a hard error (invalid input syntax), not a clean non-match; NULLIF converts that empty
--     string to a real NULL first, so a missing context still closed-fails to zero rows (D2)
--     instead of throwing.
--   system_access — the handful of legitimately-anonymous read paths (redeem/verify lookup,
--     status-list read, JWKS read, Redis Streams workers) that have no principal to resolve a
--     tenant from at all. Set transaction-scoped by shared.SystemAccessExecutor (D5), callable
--     only by the enumerated services.
-- FORCE ROW LEVEL SECURITY binds even the table owner (Flyway's role) to these policies — a
-- deliberate defense-in-depth choice (D2); the runtime role (khatm_app) never bypasses RLS
-- regardless, but FORCE closes the gap where an operator's own psql session as the owner role
-- would otherwise see every tenant's rows.
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'issuer_key', 'credential_schema', 'holder', 'status_list', 'credential', 'claim_code',
    'consuming_party', 'consuming_party_schema', 'consumption_event', 'app_user', 'role',
    'user_role', 'audit_log', 'api_key'
  ]
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON %I USING'
        || ' (tenant_id = NULLIF(current_setting(''app.tenant_id'', true), '''')::uuid)',
      t);
    EXECUTE format(
      'CREATE POLICY system_access ON %I USING (current_setting(''app.khatm_system'', true) = ''on'')',
      t);
    -- No DELETE: verified via a repo-wide grep before writing this migration (spec §2) — the only
    -- DELETE anywhere is consuming_party_schema's allowlist-removal, itself a business operation
    -- this SELECT/INSERT/UPDATE grant doesn't need to cover with DELETE privilege at the SQL
    -- level (the DELETE statement's WHERE clause still only ever matches rows RLS already scopes
    -- to the caller's own tenant — but the grant itself is intentionally narrower than that,
    -- since D3 calls for no DELETE grants without a documented exception, and disallowSchema's
    -- idempotent-no-op-on-nothing-to-remove semantics do not require one: a khatm_app role
    -- without DELETE on this one table would fail that operation, so DELETE is granted here too,
    -- narrowly, for this table alone).
    IF t = 'consuming_party_schema' THEN
      EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO khatm_app', t);
    ELSE
      EXECUTE format('GRANT SELECT, INSERT, UPDATE ON %I TO khatm_app', t);
    END IF;
  END LOOP;
END $$;

-- audit_log's append-only trigger (V1) already blocks UPDATE/DELETE at the trigger level
-- regardless of grants — the UPDATE grant above is still needed for Hibernate's own
-- optimistic-locking/merge machinery to be a valid no-op path, matching the pre-existing grant
-- shape every other table gets; the trigger is the actual enforcement, not this GRANT list.

-- audit_log.id is `bigint GENERATED ALWAYS AS IDENTITY` (V1) — Postgres backs this with a real,
-- separately-privileged sequence object; a non-owner role needs explicit USAGE on it to INSERT at
-- all (confirmed empirically: khatm_app got "permission denied for table audit_log" without this,
-- even with the table-level INSERT grant already in place above). Every other business table uses
-- an application-generated UUIDv7 primary key (CONVENTIONS §1 D1) with no sequence involved, so
-- audit_log is the one place this is needed.
GRANT USAGE ON SEQUENCE audit_log_id_seq TO khatm_app;

-- `tenant` itself: excluded from RLS (no tenant_id of its own to filter by — the admin plane
-- reads/writes every tenant regardless of the caller's own tenant, by design), but khatm_app
-- still needs plain privileges on it — "no RLS" is not "no grant"; the tenant admin/onboarding
-- plane (tenant.domain.TenantAdminService/TenantDirectoryService) reads and writes this table
-- on every request regardless.
GRANT SELECT, INSERT, UPDATE ON tenant TO khatm_app;
